name: nopDevStack
version: "3.7"
services:
    nopcommerce_web:
        build:
            context: ..
            dockerfile: ./.devcontainer/Dockerfile
            args:
                IDE_USER: "${USER:-defaultuser}"  # Default to 'defaultuser' if USER is not set
                IDE_UID: ${USERID:-1000}         # Default to '1000' if USERID is not set
                IDE_GID: ${GROUPID:-1000}        # Default to '1000' if GROUPID is not set
        user: "${USER:-defaultuser}"
        environment:
            - USER=${USER:-defaultuser}
            - USERID=${USERID:-1000}
            - GROUPID=${GROUPID:-1000}
        container_name: nopcommerce
        ports:
            - "8080:8080"
        depends_on:
            nopcommerce_database:
                condition: service_started
                required: true
        networks:
            - nop-net
        volumes:
            - type: bind
              source: ../src
              target: /workspace/src
            - type: bind
              source: ../.devcontainer
              target: /workspace/.devcontainer
            # - type: bind
            #   source: ./.vscode
            #   target: /workspace/.vscode 
        # user: vscode
    nopcommerce_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "nopCommerce_db_password"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        networks:
            - nop-net

volumes:
  nopcommerce_data:    

networks:
  nop-net:
    driver: bridge